name: Django                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-20.04                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a test step"
    needs: build

  integration:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
    continue-on-error: true
    needs: [build, test] 

  prod:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a deploy step"
    needs: [build, test, integration]

  artifact:
    runs-on: ubuntu-20.04
    steps:
      - name: Step 1 - create artifact
        run: echo "hello" > hello.txt
      
      - name: Step 2 - upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello.txt
          path: hello.txt 
    needs: [build, test, integration, prod]
